# Generated by Django 4.0.4 on 2022-05-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_alter_city_country_alter_restaurant_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='owner_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
